spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "!qkr0147258"

logging:
  level:
    org.hibernate.SQL: debug